[versions]
activityCompose = "1.9.2"
androidGradlePlugin = "8.7.2"
apollo = "3.7.1"
composeBom = "2024.09.01"
coreKtx = "1.13.1"
espressoCore = "3.6.1"
uiAutomator = "2.3.0"
hilt = "2.51.1"
hiltComposeNavigation= "1.2.0"
junit = "4.13.2"
junitExt = "1.2.1"
benchmarkMacroJunit = "1.3.0"
profileInstaller = "1.3.1"
kotlin = "2.0.0"
kotlinKsp = "2.0.0-1.0.21"
coil = "2.7.0"
lifecycleRuntimeKtx = "2.8.5"
navigationCompose = "2.8.0"
room = "2.6.1"
dataStore = "1.1.1"
shapes = "1.0.1"
materialKolor = "1.7.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom"}
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }

apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltComposeNavigation"}
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}

androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "shapes"}
androidx-graphics-shapes-android = { module = "androidx.graphics:graphics-shapes-android", version.ref = "shapes"}

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt"}
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-ui-automator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit" }
androidx-profile-installer = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileInstaller" }

material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
daggerHiltAndroidGradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }